#!/bin/bash

sudo cp xgterm /usr/local/bin/xgterm

cd /usr/local/bin

sudo chmod 777 xgterm

cd

sudo apt-get update

sudo apt-get install tcsh 

sudo mkdir /iraf

sudo mkdir /iraf/iraf

sudo mv iraf.lnux.x86_64.tar.gz /iraf/iraf/.

cd /iraf/iraf

sudo tar -zxf iraf.lnux.x86_64.tar.gz

sudo rm iraf.lnux.x86_64.tar.gz

sudo ./install

sudo mkdir /iraf/x11iraf

cd

sudo mv x11iraf-v2.0BETA-bin.linux.tar.gz /iraf/x11iraf

cd /iraf/x11iraf

sudo tar -zxf x11iraf-v2.0BETA-bin.linux.tar.gz

sudo rm x11iraf-v2.0BETA-bin.linux.tar.gz

sudo ./install

cd

sudo tar -zxf ds9.linux64.7.2.tar.gz

sudo rm ds9.linux64.7.2.tar.gz

sudo mv ds9 /usr/local/bin/.

cd

mkdir IRAF

cd IRAF

mkiraf

cd

sudo cp xgterm /usr/local/bin/xgterm

sudo rm xgterm

sudo rm installIRAF

exit

